### ISSUE TITLE
Schema.prisma file not found when running full docker-compose project

### ISSUE THREAD

**Issue by gmconte** [truefoundry/cognita#282] opened 2024-07-19 15:25 UTC
Environment:
* Ubuntu Linux 20.04
* VSCode (latest)
* DevContainer based on python:1-3.12-bullseye

When running the docker-compose command described in the readme, the cognita-backend service fails because it can't access the database/schema.prisma file:
`Error: Provided --schema at ./backend/database/schema.prisma doesn't exist.`

The culprit is in the volumes configuration in the `docker-compose.yaml` file, which overrides the folder copied by the backend Dockerfile.

A simple workaround is to add a comment on the volume line under the cognita-backend service:
```
volumes:
    #- .:/app    <-- comment this line
    - ./volumes/pgdata:/var/lib/postgresql/data
    - ./volumes/user_data:/app/user_data
```

After that, everything worked well, but I was wondering why the duplication and why it doesn't work (I don't have enough experience with docker-compose volumes)

Hope it helps others with the same problem

**Comment by S1LV3RJ1NX** [comment] 2024-07-21 14:16
Not sure, what is the issue here, but I am not able to reproduce this on my end. 
@chiragjn any help here?

**Comment by chiragjn** [comment] 2024-07-23 07:40
I am able to reproduce this, I am pushing a fix in a while

**Comment by chiragjn** [comment] 2024-07-23 08:11
Actually I am not able to reproduce this, even though the docker compose replaces the app dir, as long as you have the schema.prisma on the host (it should be as it is committed to the repo) it should work
I tried setting it up from scratch and did not run into this

**Comment by chiragjn** [comment] 2024-07-25 09:37
I am closing this for now, pleae re-open if you are still facing this issue

**Closed by chiragjn** 2024-07-25 09:37 UTC
